<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistPhpunit6TestResultParser' => 'src/unit/parser/ArcanistPhpunit6TestResultParser.php',
    'Phpunit6TestEngine' => 'src/unit/engine/Phpunit6TestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistPhpunit6TestResultParser' => 'ArcanistTestResultParser',
    'Phpunit6TestEngine' => 'ArcanistUnitTestEngine',
  ),
));
